CREATE TABLE IF NOT EXISTS rating (
    rating_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50)
);

CREATE TABLE IF NOT EXISTS films (
    film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name varchar(100),
    description varchar(200),
    release_date date,
    duration int,
    rating_id integer REFERENCES rating,
    rate long
);

CREATE TABLE IF NOT EXISTS genres (
   genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   genre_title varchar(50)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id integer REFERENCES films,
    genre_id integer REFERENCES genres
);

CREATE TABLE IF NOT EXISTS users (
   user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   email varchar,
   login varchar,
   user_name varchar,
   birthday date
);

CREATE TABLE IF NOT EXISTS likes (
    film_id integer REFERENCES films,
    liked_user_id integer REFERENCES users
);

CREATE TABLE IF NOT EXISTS friends (
    user_id integer NOT NULL REFERENCES users,
    friend_id integer NOT NULL REFERENCES users,
    status boolean
);

